config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#about'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/resume' => 'static_pages#resume'
  get '/cata/:id', to: 'static_pages#cata'
  get '/cata' => 'static_pages#cata'
  get '/download' => 'static_pages#download'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def resume
  end

  def cata
  end
  
  def download
    send_file(
      Rails.root.join('app' , 'assets', 'resources', 'BrandonBielickiResume.pdf'),
      filename: "BrandonBielickiResume.pdf",
      type: "application/pdf"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <%= yield :title %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div id="container">
		<div id="nav-container">
			<div id="nav-bar">
              
              
                <%= link_to '<p class="nav-unselected home-link" id="home">Brandon Bielicki</p>'.html_safe,
                    about_path%>
				<a href="#"><p id="menu-icon" class="fa fa-bars fa-md"></p></a>
				
				
				<ul id ="social">
					<li><a href="http://github.com/brandonbielicki"class="nav-unselected nav-icon"><p class="fa nav-icon fa-git-square fa-md"></p></a></li>
					<li><a href="http://linkedin.com/pub/brandon-bielicki/97/a52/943"class="nav-unselected nav-icon"><p class="fa nav-icon fa-linkedin-square fa-md"></p></a></li>
					<li><a href="mailto:brandonbielicki@gmail.com"class="nav-unselected nav-icon"><p class="fa nav-icon fa-envelope-square fa-md"></p></a></li>
				</ul>
				<ul id="nav-menu">
                    <li>
                        <%= link_to '<p id="resume-tab" class="nav-right resume-link nav-unselected">Resume</p>'.html_safe,
                            resume_path %>
                    </li>
                    <li>
                        <%= link_to '<p id="contact-tab" class="nav-right contact-link nav-unselected">Contact</p>'.html_safe,
                            contact_path %>
                    </li>
                    <li>
                        <%= link_to '<p id="about-tab" class="nav-right about-link nav-unselected">About</p>'.html_safe,
                            about_path %>
                    </li>
				</ul>
				
				
			</div>
		</div>

        <%= yield :top %>

		<div id="main-body">
            <%= yield :main %>
		</div>
		<div id="footer">
			<div id="footer-social">
                <div id="nav-centered">
                    <ul>
                        <li><a href="https://www.facebook.com/brandon.bielicki" class="footer-icon"><p class="fa footer-icon fa-facebook-square fa-lg"></p></a></li>
                        <li><a href="https://twitter.com/brandonbielicki" class="footer-icon"><p class="fa footer-icon fa-twitter-square fa-lg"></p></a></li>
                        <li><a href="http://github.com/brandonbielicki" class="footer-icon"><p class="fa footer-icon fa-git-square fa-lg"></p></a></li>
                        <li><a href="http://linkedin.com/pub/brandon-bielicki/97/a52/943" class="footer-icon"><p class="fa footer-icon fa-linkedin-square fa-lg"></p></a></li>
                        <li><a href="mailto:brandonbielicki@gmail.com" class="footer-icon"><p class="fa fa-envelope-square footer-icon fa-lg"></p></a></li>
                    </ul>
                </div>
            </div>
            <p id="signature" class="text-center">Ruby on Rails | Twitter Bootstrap</p>
		</div>
	</div>
</body>
</html>

app/views/static_pages/about.html.erb
<% content_for :title do %>
    <title>About</title>
<% end %>

<% content_for :top do %>
  <div id="top">
      <div id="top-content">
          <h1 id="large-header">Brandon Bielicki</h1>
          <p id="small-header">Programmer, Web Developer</p>
          <div id="header-buttons">
              <%= link_to '<p>CONTACT</p>'.html_safe, contact_path, {:class=>"hollow-button-white"} %>
              <%= link_to '<p>RESUME</p>'.html_safe, resume_path, {:class=>"hollow-button-white"} %>
          </div>
      </div>
  </div>
<% end %>

<% content_for :main do %>
    <img id="construction" src="<%= asset_url("underConstruction.png") %>">
<% end %>

app/views/static_pages/cata.html.erb
<% content_for :main do %>
    <div id="timer-container">
        <p>Bus # : </p>
        <input id="bus-select" type="number" value="<%= params[:id] %>">
        <p id="timer"></p>
    </div>
    
    <div id="map"> </div>
    
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCVATUIwaa1i_ZdBwp05D1u06d0Qlc1-p4&callback=initMap">
    </script>
<% end %>

app/views/static_pages/contact.html.erb
<% content_for :title do %>
    <title>Contact</title>
<% end %>

<% content_for :top do %>  
   
<% end %>

<% content_for :main do %>

<div id="contact-container-top">
    <div id="contact-info">
        <div id="contact-info-title">
            <h1 class="ubuntu">CONTACT INFORMATION</h1><br>
        </div>
        <div id="contact-info-content">
            <p class="ubuntu-med">Brandon Bielicki</p><br>
            <p class="ubuntu">East Lansing, MI 48823</p><br>
            <a href="tel:248-877-3544"><p class="ubuntu underlined">248.877.3544</p></a><br>
            <a href="mailto:brandonbielicki@gmail.com"><p class="ubuntu underlined">BrandonBielicki@gmail.com</p></a>
        </div>
        <div id="contact-info-resume">
            <%= link_to '<p>Download Resume</p>'.html_safe, download_path, {:class=>"hollow-button-black"} %>
        </div>
    </div>
      
    <div id="contact-pic">
      <img src="<%= asset_url("matrix.jpg") %>">
    </div>
</div>

<div id="contact-note">
  <hr>
</div>
    
<% end %>

app/views/static_pages/resume.html.erb
<% content_for :title do %>
    <title>Resume</title>
<% end %>

<% content_for :top do %>  
   
<% end %>

<% content_for :main do %>

    <div id="resume-container">
		<img id="resume-img" src="<%= asset_url("BrandonBielickiResume.jpg") %>">
	</div>    
<% end %>